name: 'Install Flutter SDK'
description: 'Dart and Flutter CLIs available for your GitHub Action'
author: 'Marcin Wróblewski'
branding:
  color: 'white'
  icon: 'download'
inputs:
  channel:
    description: 'Desired Flutter channel'
    required: false
    default: 'stable'
runs:
  using: 'composite'
  steps:
    - run: chmod +x $GITHUB_ACTION_PATH/install-flutter-sdk.sh
      shell: bash
    - run: $GITHUB_ACTION_PATH/install-flutter-sdk.sh -c ${{ inputs.channel }}
      shell: bash